application: storystream-analytics
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: 2.6
- name: markupsafe
  version: latest

handlers:
- url: /static
  static_dir: static
  login: required
  secure: never

- url: /admin/proxy/.*
  script: controllers.admin.app
  login: admin
  secure: never

- url: /admin.*
  script: controllers.owner.app
  login: required
  secure: never

- url: /management.*
  script: controllers.management.app
  secure: never

- url: /.*
  script: controllers.public.app
  secure: never
